# Generated by Django 6.0.1 on 2026-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
    ]
